debug: true
server:
  port: 8086
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: '/shenhua'
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  http:
   encoding:
      charset: UTF-8
      enabled: true
      force: true
  # AOP 配置
  aop:
    proxy-target-class: true
  datasource:
    druid:
      #driver-class-name: oracle.jdbc.driver.OracleDriver
      #url: jdbc:oracle:thin:@133.96.10.118:1533:WOSLCH
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://rm-8vb63id3264r63f35po.mysql.zhangbei.rds.aliyuncs.com:3306/shenhua?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: shenhua
      password: shenhua615715!
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      #validationQuery: select 'x'
      testWhileIdle: false
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      #poolPreparedStatements: true
      #maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true

mybatis:
  type-aliases-package: com.shenhua.base.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名规则
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  mappers:
    - com.shenhua.base.myMapper.MyMapper
  not-empty: false
  identity: ORACLE

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  #file: shenhua_admin_server.log
  level:
    com.shenhua.service: debug
    com.shenhua.controller: debug
  config: classpath:logging-config.xml

#可匿名访问的链接
jwt:
  accessTokenExpireTime: 30 #token5分钟过期一次
  shiroCacheExpireTime: 30 #5分钟过期一次  默认和accessTokenExpireTime保持一致
  refreshTokenExpireTime: 1800 #单位秒 半小时自动退出
  encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==   # JWT认证加密私钥(Base64加密)

redis:
  sentinelMode: false
  mymaster:
    masterName: contest26-redis
  sentinel:
    hostName: 10.125.128.28
    hostName2: 10.125.128.35
    port: 9051
  host: 127.0.0.1
  port: 6379
  password: redis_pass_1029384756
  database: 0